Repository DevOps-MBSE/AaC, pull requests merged in 2021-11, with the labels that each got.

#84 Feature/gen protobuf
  .editorconfig
  .vscode/launch.json
  model/protobuf_flow/Data.yaml
  model/protobuf_flow/Services.yaml
  model/protobuf_flow/Subsystem.yaml
  model/protobuf_flow/System.yaml
  model/protobuf_flow/flow.yaml
  plugins/gen-protobuf/README.md
  plugins/gen-protobuf/aac-gen-protobuf.yaml
  plugins/gen-protobuf/aac_gen_protobuf/__init__.py
  plugins/gen-protobuf/aac_gen_protobuf/aac_gen_protobuf.py
  plugins/gen-protobuf/aac_gen_protobuf/aac_gen_protobuf_impl.py
  plugins/gen-protobuf/aac_gen_protobuf/templates/message.proto.jinja2
  plugins/gen-protobuf/setup.py
  plugins/gen-protobuf/tests/test_aac_gen_protobuf_impl.py
  src/aac/AacCommand.py
  src/aac/cli.py
  src/aac/genplug.py
  src/aac/hookspecs.py
  src/aac/plugins.py
  src/aac/template_engine.py
  src/aac/templates/genplug/__init__.py.jinja2
  src/aac/templates/genplug/plugin.py.jinja2
  src/aac/templates/genplug/plugin_impl.py.jinja2
  src/aac/templates/genplug/setup.py.jinja2
  src/aac/validator.py
  tests/test_genplug.py
  tests/test_template_engine.py
  tests/test_util.py
  tests/test_validator.py
  tox.ini
Labels: enhancement

#74 Auto-Generate System Design Document
  .vscode/launch.json
  model/aac/AaC_CLI.yaml
  plugins/aac-spec/aac-spec.yaml
  plugins/gen-design-doc/aac-gen-design-doc.yaml
  plugins/gen-design-doc/aac_gen_design_doc/__init__.py
  plugins/gen-design-doc/aac_gen_design_doc/aac_gen_design_doc.py
  plugins/gen-design-doc/aac_gen_design_doc/aac_gen_design_doc_impl.py
  plugins/gen-design-doc/aac_gen_design_doc/templates/datum.md.jinja2
  plugins/gen-design-doc/aac_gen_design_doc/templates/macros.jinja2
  plugins/gen-design-doc/aac_gen_design_doc/templates/model.md.jinja2
  plugins/gen-design-doc/aac_gen_design_doc/templates/system-design-doc.md.jinja2
  plugins/gen-design-doc/aac_gen_design_doc/templates/usecase.md.jinja2
  plugins/gen-design-doc/setup.py
  plugins/gen-design-doc/tests/test_aac_gen_design_doc_impl.py
  src/aac/genplug.py
  src/aac/template_engine.py
  src/aac/templates/genplug/plugin_impl.py.jinja2
  tests/test_genplug.py
Labels: enhancement

#97 Bug - Can't Validate Root Extension
  src/aac/validator.py
  tests/test_validator.py
Labels: bug

#106 Generate Gherkin feature files from Model behaviors
  .vscode/launch.json
  model/flow/ServiceOne.yaml
  model/flow/ServiceThree.yaml
  model/flow/ServiceTwo.yaml
  model/flow/Subsystem.yaml
  model/flow/System.yaml
  plugins/gen-gherkin-behaviors/aac-gen-gherkin-behaviors.yaml
  plugins/gen-gherkin-behaviors/aac_gen_gherkin_behaviors/__init__.py
  plugins/gen-gherkin-behaviors/aac_gen_gherkin_behaviors/aac_gen_gherkin_behaviors.py
  plugins/gen-gherkin-behaviors/aac_gen_gherkin_behaviors/aac_gen_gherkin_behaviors_impl.py
  plugins/gen-gherkin-behaviors/aac_gen_gherkin_behaviors/templates/behavior.feature.jinja2
  plugins/gen-gherkin-behaviors/setup.py
  plugins/gen-gherkin-behaviors/tests/test_aac_gen_gherkin_behaviors_impl.py
  src/aac/parser.py
Labels: enhancement

#102 Simplify Model Behavior
  model/aac/AaC.yaml
  model/flow/External.yaml
  model/flow/flow.yaml
Labels: enhancement

#90 I want Genplugin to generate a README file
  src/aac/genplug.py
  src/aac/templates/genplug/README.md.jinja2
  tests/test_genplug.py
Labels: enhancement

#107 Add Python types for GenPlugin Model Inputs
  .github/workflows/python-app.yml
  .vscode/launch.json
  plugins/aac-plantuml/aac-plantuml.yaml
  plugins/aac-spec/aac-spec.yaml
  plugins/gen-design-doc/aac-gen-design-doc.yaml
  plugins/gen-gherkin-behaviors/aac-gen-gherkin-behaviors.yaml
  plugins/gen-protobuf/aac-gen-protobuf.yaml
  src/aac/genplug.py
  src/aac/templates/genplug/setup.py.jinja2
  src/aac/validator.py
  tests/test_genplug.py
Labels: bug

#91 I want Genplugin to generate my plugin with a proper directory structure
  src/aac/genplug.py
Labels: enhancement

#122 Added gitpod badge to readme
  README.md
Labels: nice to have
