Repository DevOps-MBSE/AaC, pull requests merged in 2022-07, with the labels that each got.

#388 I want the LSP Hover Request to show the structure of a definition when I hover over its name
  python/src/aac/lang/lsp/language_server.py
  python/src/aac/lang/lsp/providers/hover_provider.py
  python/tests/helpers/lsp/responses/hover_response.py
  python/tests/lang/lsp/test_hover_provider.py
Labels: feature: AaC LSP

#395 Added python version check
  python/src/aac/__init__.py
Labels: nice to have

#392 Some tests can fail due to path idiosyncrasies on MacOS versus Linux
  python/tests/__init__.py
  python/tests/io_tests/test_parser.py
Labels: bug, good first issue, tech debt, draft
