Repository DevOps-MBSE/AaC, pull requests merged in 2022-02, with the labels that each got.

#212 Bugfix gen puml template
  python/src/aac/plugins/gen_plant_uml/gen_plant_uml_impl.py
  python/src/aac/templates/gen_plant_uml/component/component_diagram.puml.jinja2
  python/tests/plugins/test_gen_plant_uml.py
Labels: bug

#230 Update gen-json to create output directories if they do not exist
  python/src/aac/plugins/gen_json/gen_json_impl.py
  python/tests/plugins/test_gen_json.py
Labels: bug

#225 216 Add Template AaC Repository
  README.md
Labels: documentation

#232 Refactor _get_all_extension_errors in validator
  python/src/aac/validator.py
  python/tox.ini
  vscode_extension/src/AacLanguageServer.ts
Labels: tech debt

#237 Update Deploy Python Artifact Workflow
  .github/workflows/python-deploy-artifacts.yml
Labels: bug
