Repository DevOps-MBSE/AaC, pull requests merged in 2022-10, with the labels that each got.

#270 Create the Unique Name validation plugin
  .dir-locals.el
  .github/workflows/python-build-artifacts.yml
  .github/workflows/python-tests.yml
  aac.el
  python/model/calc/model/calculator.yaml
  python/model/plugin/plugin.yaml
  python/setup.py
  python/src/aac/io/parser/_parse_source.py
  python/src/aac/io/paths.py
  python/src/aac/lang/definition_helpers.py
  python/src/aac/lang/definitions/definition.py
  python/src/aac/lang/definitions/lexeme.py
  python/src/aac/lang/definitions/search.py
  python/src/aac/plugins/material_model/material_model.yaml
  python/src/aac/plugins/plugin_manager.py
  python/src/aac/plugins/rest_api/models/definition_model.py
  python/src/aac/plugins/validators/defined_references/defined_references.yaml
  python/src/aac/plugins/validators/unique_names/__init__.py
  python/src/aac/plugins/validators/unique_names/_unique_names.py
  python/src/aac/plugins/validators/unique_names/unique_names.yaml
  python/src/aac/spec/spec.yaml
  python/tests/helpers/assertion.py
  python/tests/helpers/parsed_definitions.py
  python/tests/io_tests/test_parser.py
  python/tests/lang/test_definition.py
  python/tests/plugins/test_gen_gherkin_behaviors.py
  python/tests/plugins/test_gen_json.py
  python/tests/plugins/test_gen_plugin.py
  python/tests/plugins/test_rest_api.py
  python/tests/plugins/validators/test__unique_names.py
  python/tests/plugins/validators/test_defined_references.py
  python/tests/plugins/validators/test_required_fields.py
  python/tests/plugins/validators/test_root_keys.py
  python/tests/plugins/validators/test_validate_exclusive_fields.py
  python/tests/plugins/validators/test_validation_implementation_plugin.py
Labels: enhancement

#457 Enhance the VSCode "Getting Started" experience
  docs/assets/images/vscode_extension/aac-commands-cli.png
  docs/assets/images/vscode_extension/aac-commands-vscode.png
  docs/assets/images/vscode_extension/aac-extension-applied.png
  docs/assets/images/vscode_extension/aac-extension-settings.png
  docs/assets/images/vscode_extension/example-code-completion.png
  docs/assets/images/vscode_extension/example-command-output.png
  docs/assets/images/vscode_extension/example-command-selection.png
  docs/assets/images/vscode_extension/example-find-references-afterwards.png
  docs/assets/images/vscode_extension/example-find-references.png
  docs/assets/images/vscode_extension/example-go-to-definition-afterwards.png
  docs/assets/images/vscode_extension/example-go-to-definition.png
  docs/assets/images/vscode_extension/example-go-to-references-afterwards.png
  docs/assets/images/vscode_extension/example-go-to-references-picker.png
  docs/assets/images/vscode_extension/example-go-to-references.png
  docs/assets/images/vscode_extension/example-hover.png
  docs/assets/images/vscode_extension/example-optional-command-argument.png
  docs/assets/images/vscode_extension/example-rename-afterwards.png
  docs/assets/images/vscode_extension/example-rename-new-name.png
  docs/assets/images/vscode_extension/example-rename.png
  docs/assets/images/vscode_extension/example-required-command-argument.png
  docs/assets/images/vscode_extension/execute-aac-command.png
  docs/assets/images/vscode_extension/install-aac-extension.png
  docs/assets/images/vscode_extension/open-settings.png
  docs/docs/user_guide/index.md
  docs/docs/vscode_extension/command_features.md
  docs/docs/vscode_extension/index.md
  docs/docs/vscode_extension/lsp_features.md
  vscode_extension/README.md
  vscode_extension/media/aac-command.md
  vscode_extension/media/aac-path.md
  vscode_extension/media/view-docs.md
  vscode_extension/package.json
  vscode_extension/src/AacLanguageServer.ts
  vscode_extension/src/aacExecutableWrapper.ts
  vscode_extension/src/configuration.ts
  vscode_extension/src/extension.ts
  vscode_extension/src/helpers.ts
  vscode_extension/src/test/suite/aacExecutableWrapper.test.ts
Labels: documentation, enhancement, feature: VSCode extension

#466 Hotfix: Inherited Fields not Visible in Active Context
  python/src/aac/lang/language_context.py
  python/src/aac/validate/_validate.py
  python/tests/lang/definitions/test_inheritance.py
Labels: bug

#412 I want a Semantic Token Provider for the VSCode Extension
  .dir-locals.el
  docs/assets/images/vscode_extension/example-semantic-token-enum-values.png
  docs/assets/images/vscode_extension/example-semantic-token-enum.png
  docs/assets/images/vscode_extension/example-semantic-token-keyword.png
  docs/assets/images/vscode_extension/example-semantic-token-macro.png
  docs/assets/images/vscode_extension/example-semantic-token-string.png
  docs/assets/images/vscode_extension/example-semantic-token-struct.png
  docs/docs/vscode_extension/lsp_features.md
  python/src/aac/io/parser/_parse_source.py
  python/src/aac/lang/definitions/definition.py
  python/src/aac/plugins/lsp_server/language_server.py
  python/src/aac/plugins/lsp_server/providers/goto_definition_provider.py
  python/src/aac/plugins/lsp_server/providers/semantic_tokens_provider.py
  python/tests/helpers/lsp/responses/semantic_tokens_response.py
  python/tests/plugins/lsp_server/base_lsp_test_case.py
  python/tests/plugins/lsp_server/lsp_test_client.py
  python/tests/plugins/lsp_server/providers/test_goto_definition_provider.py
  python/tests/plugins/lsp_server/providers/test_semantic_tokens_provider.py
  vscode_extension/src/AacLanguageServer.ts
  vscode_extension/src/aacExecutableWrapper.ts
Labels: feature: AaC LSP

#409 I want tab-completion for the AaC package
  .github/workflows/python-tests.yml
  .vscode/python.code-workspace
  docs/docs/user_guide/aac_cli.md
  python/model/plugin/plugin.yaml
  python/setup.py
  python/src/aac/__main__.py
  python/src/aac/cli/aac_command.py
  python/src/aac/cli/builtin_commands/validate/__init__.py
  python/src/aac/cli/builtin_commands/validate/validate.yaml
  python/src/aac/cli/builtin_commands/version/__init__.py
  python/src/aac/cli/builtin_commands/version/version_impl.py
  python/src/aac/cli/execute.py
  python/src/aac/plugins/first_party/gen_design_doc/__init__.py
  python/src/aac/plugins/first_party/gen_design_doc/gen_design_doc.yaml
  python/src/aac/plugins/first_party/gen_design_doc/gen_design_doc_impl.py
  python/src/aac/plugins/first_party/gen_gherkin_behaviors/__init__.py
  python/src/aac/plugins/first_party/gen_gherkin_behaviors/gen_gherkin_behaviors.yaml
  python/src/aac/plugins/first_party/gen_gherkin_behaviors/gen_gherkin_behaviors_impl.py
  python/src/aac/plugins/first_party/gen_json/__init__.py
  python/src/aac/plugins/first_party/gen_json/gen_json.yaml
  python/src/aac/plugins/first_party/gen_json/gen_json_impl.py
  python/src/aac/plugins/first_party/gen_plant_uml/__init__.py
  python/src/aac/plugins/first_party/gen_plant_uml/gen_plant_uml.yaml
  python/src/aac/plugins/first_party/gen_plant_uml/gen_plant_uml_impl.py
  python/src/aac/plugins/first_party/gen_plugin/__init__.py
  python/src/aac/plugins/first_party/gen_plugin/gen_plugin.yaml
  python/src/aac/plugins/first_party/gen_plugin/gen_plugin_impl.py
  python/src/aac/plugins/first_party/gen_plugin/templates/first_party/__init__.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/first_party/plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/README.md.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/__init__.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/setup.py.jinja2
  python/src/aac/plugins/first_party/gen_protobuf/__init__.py
  python/src/aac/plugins/first_party/gen_protobuf/gen_protobuf.yaml
  python/src/aac/plugins/first_party/gen_protobuf/gen_protobuf_impl.py
  python/src/aac/plugins/first_party/help_dump/__init__.py
  python/src/aac/plugins/first_party/help_dump/help-dump.yaml
  python/src/aac/plugins/first_party/help_dump/help_dump_impl.py
  python/src/aac/plugins/first_party/lsp_server/__init__.py
  python/src/aac/plugins/first_party/lsp_server/lsp-server.yaml
  python/src/aac/plugins/first_party/lsp_server/start_lsp_server_impl.py
  python/src/aac/plugins/first_party/material_model/__init__.py
  python/src/aac/plugins/first_party/material_model/material_model_impl.py
  python/src/aac/plugins/first_party/print_spec/__init__.py
  python/src/aac/plugins/first_party/print_spec/print_spec_impl.py
  python/src/aac/plugins/first_party/rest_api/__init__.py
  python/src/aac/plugins/first_party/rest_api/aac_rest_api_impl.py
  python/src/aac/plugins/first_party/rest_api/rest_api.yaml
  python/src/aac/plugins/first_party/specifications/__init__.py
  python/src/aac/plugins/first_party/specifications/specifications.yaml
  python/src/aac/plugins/first_party/specifications/specifications_impl.py
  python/src/aac/plugins/plugin_execution.py
  python/src/aac/plugins/plugin_manager.py
  python/src/aac/spec/spec.yaml
  python/tests/cli/test_execute.py
  python/tests/plugins/first_party/test_gen_plugin.py
  python/tests/test_spec_core.py
Labels: enhancement
