Repository DevOps-MBSE/AaC, pull requests merged in 2023-01, with the labels that each got.

#507 Validation Documentation
  docs/docs/dev_guide/validation_plugins.md
Labels: documentation

#445 I want CLI commands to manage AaC Plugins
  .github/workflows/python-cross-platform-support.yml
  .github/workflows/python-test-python-version.yml
  .gitignore
  python/src/aac/cli/execute.py
  python/src/aac/lang/active_context_lifecycle_manager.py
  python/src/aac/lang/language_context.py
  python/src/aac/plugins/first_party/gen_design_doc/__init__.py
  python/src/aac/plugins/first_party/gen_gherkin_behaviors/__init__.py
  python/src/aac/plugins/first_party/gen_json/__init__.py
  python/src/aac/plugins/first_party/gen_plant_uml/__init__.py
  python/src/aac/plugins/first_party/gen_plant_uml/gen_plant_uml_impl.py
  python/src/aac/plugins/first_party/gen_plugin/__init__.py
  python/src/aac/plugins/first_party/gen_plugin/gen_plugin_impl.py
  python/src/aac/plugins/first_party/gen_plugin/templates/first_party/__init__.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/first_party/plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/first_party/test_plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/README.md.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/__init__.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_plugin/templates/third_party/test_plugin_impl.py.jinja2
  python/src/aac/plugins/first_party/gen_protobuf/__init__.py
  python/src/aac/plugins/first_party/help_dump/__init__.py
  python/src/aac/plugins/first_party/lsp_server/__init__.py
  python/src/aac/plugins/first_party/material_model/__init__.py
  python/src/aac/plugins/first_party/plugin_management/__init__.py
  python/src/aac/plugins/first_party/plugin_management/plugin-management.yaml
  python/src/aac/plugins/first_party/plugin_management/plugin_management_impl.py
  python/src/aac/plugins/first_party/primitive_type_check/__init__.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/__init__.py
  python/src/aac/plugins/first_party/print_spec/__init__.py
  python/src/aac/plugins/first_party/print_spec/print_spec_impl.py
  python/src/aac/plugins/first_party/rest_api/__init__.py
  python/src/aac/plugins/first_party/specifications/__init__.py
  python/src/aac/plugins/plugin_execution.py
  python/src/aac/plugins/plugin_manager.py
  python/src/aac/templates/engine.py
  python/tests/plugins/first_party/test_gen_json.py
  python/tests/plugins/first_party/test_gen_plugin.py
  python/tests/plugins/first_party/test_plugin_management_impl.py
Labels: feature: Python package

#525 CLI errors don't return error codes
  .github/workflows/python-cross-platform-support.yml
  .github/workflows/python-test-python-version.yml
  python/src/aac/__init__.py
  python/src/aac/cli/execute.py
Labels: bug
