Repository DevOps-MBSE/AaC, pull requests merged in 2023-11, with the labels that each got.

#713 Corrected site links in README
  README.md
  python/src/aac/__init__.py
Labels: changed

#717 POPO migration comments
  python/src/aac/plugins/first_party/active_context/active_context_impl.py
  python/src/aac/plugins/first_party/gen_plugin/gen_plugin_impl.py
  python/src/aac/plugins/first_party/gen_protobuf/gen_protobuf_impl.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/bool_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/date_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/file_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/int_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/num_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/reference_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/string_validator.py
  python/src/aac/plugins/validators/defined_references/_validate_references.py
  python/src/aac/plugins/validators/enum_values/_validate_enums.py
  python/src/aac/plugins/validators/exclusive_fields/_validate_exclusive_fields.py
  python/src/aac/plugins/validators/reference_fields/_validate_reference_fields.py
  python/src/aac/plugins/validators/reference_targets/_validate_reference_targets.py
  python/src/aac/plugins/validators/required_fields/_validate_required_fields.py
  python/src/aac/plugins/validators/requirement_references/_validate_requirement_references.py
  python/src/aac/plugins/validators/root_keys/_validate_root_keys.py
  python/src/aac/plugins/validators/subcomponent_type/_validate_subcomponent_type.py
  python/tests/plugins/first_party/test_rest_api.py
Labels: enhancement

#719 Popo validator comments
  python/src/aac/plugins/validators/reference_fields/_validate_reference_fields.py
  python/src/aac/plugins/validators/required_fields/_validate_required_fields.py
Labels: added

#718 Investigate impacts of popo in language context system
  python/src/aac/lang/definitions/collections.py
  python/src/aac/lang/definitions/definition.py
  python/src/aac/lang/definitions/extensions.py
  python/src/aac/lang/definitions/inheritance.py
  python/src/aac/lang/definitions/json_schema.py
  python/src/aac/lang/definitions/metadata_structure.py
  python/src/aac/lang/definitions/references.py
  python/src/aac/lang/definitions/schema.py
  python/src/aac/lang/definitions/search.py
  python/src/aac/lang/definitions/structural_node.py
  python/src/aac/lang/definitions/structure.py
  python/src/aac/lang/hierarchy.py
  python/src/aac/lang/language_context.py
  python/src/aac/plugins/validators/reference_fields/_validate_reference_fields.py
Labels: added

#748 Remove constants from gen design doc plugin
  python/src/aac/__init__.py
  python/tests/plugins/first_party/test_gen_design_doc_impl.py
  python/tests/plugins/first_party/test_gen_gherkin_behaviors.py
Labels: added, removed

#749 Document primitive validation plugins
  docs/source/project_documentation/dev_guide/aac_validation.md
  docs/source/project_documentation/dev_guide/plugin_dev_guide.md
  docs/source/project_documentation/dev_guide/validation_plugins.md
  python/src/aac/__init__.py
  python/tests/plugins/first_party/test_gen_gherkin_behaviors.py
Labels: changed

#750 Add the AaC Project Structure page
  docs/source/project_documentation/dev_guide/index.rst
  docs/source/project_documentation/dev_guide/project_structure.md
  python/src/aac/__init__.py
Labels: added

#751 Document validator results
  docs/source/project_documentation/dev_guide/aac_validation.md
  docs/source/project_documentation/dev_guide/validation_plugins.md
  python/src/aac/__init__.py
Labels: added

#754 Site Corrections
  .github/workflows/sphinx.yml
  README.md
  python/src/aac/__init__.py
Labels: changed
