Repository DevOps-MBSE/AaC, pull requests merged in 2023-09, with the labels that each got.

#668 Adding Usecase Documentation
  .github/workflows/main-branch.yml
  docs/source/project_documentation/user_guide/definition_types.rst
  docs/source/project_documentation/user_guide/index.rst
  docs/source/project_documentation/user_guide/model_definitions.md
  docs/source/project_documentation/user_guide/usecase_definitions.md
  python/src/aac/__init__.py
Labels: documentation

#689 Restoring automated page deply
  .github/workflows/main-branch.yml
  python/src/aac/__init__.py
Labels: automation

#690 Lizzcondrey/revert autobuild and deploy documentation
  .github/workflows/main-branch.yml
  python/src/aac/__init__.py
Labels: bug, automation

#693 Adding release notes template
  .github/pull_request_template.md
  .github/release.yml
  python/src/aac/__init__.py
Labels: automation, added, changed

#694 Create usecase action references validator
  python/src/aac/__init__.py
  python/src/aac/plugins/validators/usecase_actions/__init__.py
  python/src/aac/plugins/validators/usecase_actions/_validate_usecase_actions.py
  python/src/aac/plugins/validators/usecase_actions/usecase_actions.yaml
  python/src/aac/spec/spec.yaml
  python/tests/helpers/parsed_definitions.py
  python/tests/plugins/first_party/test_gen_design_doc_impl.py
  python/tests/plugins/first_party/test_gen_plant_uml.py
  python/tests/plugins/validators/test__validate_usecase_actions.py
Labels: enhancement, feature: Python package, added, changed

#688 Enum Value Validator
  python/model/alarm_clock/structures.yaml
  python/model/calc/model/MathFunction.yaml
  python/model/plugin/definitions.yaml
  python/model/protobuf_flow/Data.aac
  python/src/aac/__init__.py
  python/src/aac/lang/definitions/schema.py
  python/src/aac/lang/definitions/structure.py
  python/src/aac/lang/language_context.py
  python/src/aac/plugins/first_party/gen_json/gen_json.yaml
  python/src/aac/plugins/first_party/gen_plugin/gen_plugin.yaml
  python/src/aac/plugins/validators/enum_values/__init__.py
  python/src/aac/plugins/validators/enum_values/_validate_enums.py
  python/src/aac/plugins/validators/enum_values/enum_values.yaml
  python/src/aac/spec/spec.yaml
  python/src/aac/validate/_validate.py
  python/tests/lang/definitions/test_structure.py
  python/tests/plugins/first_party/test_gen_gherkin_behaviors.py
  python/tests/plugins/first_party/test_gen_json.py
  python/tests/plugins/lsp_server/providers/test_goto_definition_provider.py
  python/tests/plugins/validators/test__validate_enum_values.py
Labels: added

#697 Remove version mismatch check from state file import
  python/src/aac/__init__.py
  python/src/aac/lang/language_context.py
Labels: tech debt, nice to have, feature: Python package, removed

#698 Fixing Gherkin Feature File Template
  python/src/aac/__init__.py
  python/src/aac/plugins/first_party/gen_gherkin_behaviors/behavior.feature.jinja2
Labels: fixed
