Repository DevOps-MBSE/AaC, pull requests merged in 2023-04, with the labels that each got.

#552 I want the LSP to dynamically color keywords
  .gitignore
  vscode_extension/package.json
  vscode_extension/syntaxes/aac-syntax.json
Labels: feature: AaC LSP

#542 I want a primitive reference validation
  python/src/aac/lang/constants.py
  python/src/aac/plugins/first_party/material_model/material_model_impl.py
  python/src/aac/plugins/first_party/primitive_type_check/__init__.py
  python/src/aac/plugins/first_party/primitive_type_check/primitive_type_check.yaml
  python/src/aac/plugins/first_party/primitive_type_check/validators/bool_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/date_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/file_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/int_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/num_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/reference_validator.py
  python/src/aac/plugins/first_party/primitive_type_check/validators/string_validator.py
  python/src/aac/spec/spec.yaml
  python/src/aac/validate/_validate.py
  python/tests/helpers/prebuilt_definition_constants.py
  python/tests/plugins/first_party/test_material_model_impl.py
  python/tests/plugins/first_party/test_primitive_validation.py
  python/tests/plugins/lsp_server/providers/test_goto_definition_provider.py
  python/tests/plugins/validators/test_validate_exclusive_fields.py
  python/tests/validate/test_validate.py
Labels: enhancement

#575 Fix PUML Diagram Output
  python/src/aac/plugins/first_party/gen_plant_uml/templates/object/object_diagram.puml.jinja2
  python/src/aac/plugins/first_party/gen_plant_uml/templates/sequence/sequence_diagram.puml.jinja2
Labels: bug
