Repository DevOps-MBSE/AaC, pull requests merged in 2024-07, with the labels that each got.

#824 sphinx documentation creating pdf
  .github/workflows/python-build-and-lint.yml
  python/setup.py
  python/src/aac/__init__.py
Labels: added

#825 Adding draft templates for plugin documentation
  python/src/aac/__init__.py
  python/src/aac/plugins/gen_plugin/templates/command_example_page.jinja2
  python/src/aac/plugins/gen_plugin/templates/plugin_documentation.jinja2
Labels: added

#826 Add req link to acceptance test scenario
  python/features/calc/model/mathmessagehandler.yaml
  python/features/calc/spec/ComplexMath_PIDS.yaml
  python/features/calc/spec/SquareRoot_SRS.yaml
  python/setup.py
  python/src/aac/__init__.py
  python/src/aac/aac.aac
Labels: good first issue, added

#827 Adding Standalone Plugin Registration
  docs/requirements.txt
  docs/source/project_documentation/dev_guide/plugin_dev_guide.md
  python/setup.py
  python/src/aac/__init__.py
Labels: added, changed

#829 Expand plugin writeups
  docs/source/images/examples/check-h.png
  docs/source/images/examples/check-output.PNG
  docs/source/images/examples/check-verbose-output.png
  docs/source/images/examples/clean-h.png
  docs/source/images/examples/clean-output.png
  docs/source/images/examples/gen-plugin-code-output.png
  docs/source/images/examples/gen-plugin-doc-output.png
  docs/source/images/examples/gen-plugin-evaluate-output.png
  docs/source/images/examples/gen-plugin-evaluate-terminal.png
  docs/source/images/examples/gen-plugin-file-output.png
  docs/source/images/examples/gen-plugin-h.png
  docs/source/images/examples/gen-plugin-output-code.png
  docs/source/images/examples/gen-plugin-output-doc.png
  docs/source/images/examples/gen-plugin-output-test.png
  docs/source/images/examples/gen-plugin-terminal-output.png
  docs/source/images/examples/gen-plugin-test-output.png
  docs/source/images/examples/gen-project-evaluate-output-directory.png
  docs/source/images/examples/gen-project-evaluate-output-terminal.png
  docs/source/images/examples/gen-project-file-output.png
  docs/source/images/examples/gen-project-h.png
  docs/source/images/examples/gen-project-output-flag-directory.png
  docs/source/images/examples/gen-project-output-flag-terminal.png
  docs/source/images/examples/gen-project-terminal-output.png
  docs/source/images/examples/generate-h.png
  docs/source/images/examples/print-defs-h.png
  docs/source/images/examples/print-defs-input-command.png
  docs/source/images/examples/print-defs-output.png
  docs/source/project_documentation/plugins/check.md
  docs/source/project_documentation/plugins/gen_plugin.md
  docs/source/project_documentation/plugins/generate.md
  docs/source/project_documentation/plugins/print_defs.md
  python/src/aac/__init__.py
Labels: added

#832 Applying Docstrings to Steps
  python/features/steps/general_purpose_steps.py
  python/src/aac/__init__.py
Labels: added

#834 Despecifying plugin generating output
  docs/source/images/examples/gen-plugin-code-output.png
  docs/source/images/examples/gen-plugin-doc-output.png
  docs/source/images/examples/gen-plugin-evaluate-terminal.png
  docs/source/images/examples/gen-plugin-terminal-output.png
  docs/source/images/examples/gen-plugin-test-output.png
  docs/source/images/examples/gen-project-evaluate-output-terminal.png
  docs/source/images/examples/gen-project-output-flag-terminal.png
  docs/source/images/vscode_extension/aac-commands-cli.png
  docs/source/images/vscode_extension/aac-commands-vscode.png
  docs/source/images/vscode_extension/aac-extension-applied.png
  docs/source/images/vscode_extension/aac-extension-settings.png
  docs/source/images/vscode_extension/example-code-completion.png
  docs/source/images/vscode_extension/example-command-output.png
  docs/source/images/vscode_extension/example-command-selection.png
  docs/source/images/vscode_extension/example-find-references-afterwards.png
  docs/source/images/vscode_extension/example-find-references.png
  docs/source/images/vscode_extension/example-go-to-definition-afterwards.png
  docs/source/images/vscode_extension/example-go-to-definition.png
  docs/source/images/vscode_extension/example-go-to-references-afterwards.png
  docs/source/images/vscode_extension/example-go-to-references-picker.png
  docs/source/images/vscode_extension/example-go-to-references.png
  docs/source/images/vscode_extension/example-hover.png
  docs/source/images/vscode_extension/example-optional-command-argument.png
  docs/source/images/vscode_extension/example-rename-afterwards.png
  docs/source/images/vscode_extension/example-rename-new-name.png
  docs/source/images/vscode_extension/example-rename.png
  docs/source/images/vscode_extension/example-required-command-argument.png
  docs/source/images/vscode_extension/example-semantic-token-enum-values.png
  docs/source/images/vscode_extension/example-semantic-token-enum.png
  docs/source/images/vscode_extension/example-semantic-token-keyword.png
  docs/source/images/vscode_extension/example-semantic-token-macro.png
  docs/source/images/vscode_extension/example-semantic-token-string.png
  docs/source/images/vscode_extension/example-semantic-token-struct.png
  docs/source/images/vscode_extension/execute-aac-command.png
  docs/source/images/vscode_extension/install-aac-extension.png
  docs/source/images/vscode_extension/open-settings.png
  docs/source/project_documentation/plugins/gen_plugin.md
  python/src/aac/__init__.py
  python/src/aac/plugins/generate/generate_impl.py
Labels: changed

#835 Pages Deployment Fix
  .github/workflows/main-branch.yml
  .github/workflows/pages-deploy.yml
  docs/requirements.txt
  python/src/aac/__init__.py
Labels: fixed

#836 Correct File Name
  .github/workflows/deploy-pages.yml
  python/src/aac/__init__.py
Labels: fixed

#837 Expand example model
  docs/source/project_documentation/dev_guide/language_api/modeling_inheritance.md
  python/features/shapes/shapes.aac
  python/src/aac/__init__.py
Labels: added
