Repository DevOps-MBSE/AaC, pull requests merged in 2024-10, with the labels that each got.

#876 Improve Tests in Check Unit Tests
  python/features/alarm_clock.feature
  python/features/calc.feature
  python/features/check.feature
  python/features/counter.feature
  python/features/docs_checks.feature
  python/features/echo.feature
  python/features/flow.feature
  python/features/steps/general_purpose_steps.py
  python/src/aac/__init__.py
  python/src/aac/plugins/check/check_aac.aac
  python/tests/test_aac/plugins/check/test_check_aac.py
Labels: added

#879 Improve in out unit tests
  python/pyproject.toml
  python/src/aac/__init__.py
  python/tests/test_aac/in_out/test_paths.py
Labels: dependencies, added, removed

#882 Fix Exception Missing Location Param (#881)
  python/src/aac/__init__.py
  python/src/aac/context/definition_parser.py
Labels: bug

#883 Improve Tests in Execute Unit Tests
  python/src/aac/__init__.py
  python/src/aac/execute/aac_execution_result.py
  python/src/aac/execute/plugin_runner.py
  python/tests/test_aac/execute/my_plugin.aac
  python/tests/test_aac/execute/test_aac_execution_result.py
  python/tests/test_aac/execute/test_plugin_manager.py
  python/tests/test_aac/execute/test_plugin_runner.py
Labels: added

#884 Improve exclusive fields unit tests
  python/features/plugins/check.feature
  python/features/plugins/constraint_assignment_arguments.feature
  python/features/plugins/exclusive_fields.feature
  python/src/aac/__init__.py
  python/tests/test_aac/plugins/exclusive_fields/test_exclusive_fields.py
Labels: added, changed

#894 Improve Tests in Print Defs Unit Tests
  python/features/plugins/check.feature
  python/features/plugins/constraint_assignment_arguments.feature
  python/features/plugins/exclusive_fields.feature
  python/features/plugins/gen_plugin.feature
  python/features/plugins/primitive.feature
  python/features/plugins/print_defs.feature
  python/features/steps/gen_plugin_steps.py
  python/features/steps/general_purpose_steps.py
  python/features/steps/print_defs.py
  python/src/aac/__init__.py
  python/tests/test_aac/plugins/print_defs/test_print_aac_definitions.py
Labels: added
