Repository DevOps-MBSE/AaC, pull requests merged in 2024-09, with the labels that each got.

#865 Update Core AaC Generation Templates
  python/src/aac/__init__.py
  python/src/aac/plugins/gen_plugin/__init__.py
  python/src/aac/plugins/gen_plugin/gen_plugin_generator.aac
  python/src/aac/plugins/gen_plugin/templates/manifest_in.jinja2
  python/src/aac/plugins/gen_plugin/templates/project_readme.jinja2
  python/src/aac/plugins/gen_plugin/templates/project_setup.jinja2
  python/src/aac/plugins/gen_plugin/templates/project_tox.jinja2
  python/src/aac/plugins/gen_plugin/templates/pyproject_toml.jinja2
  python/tests/test_aac/context/test_definition_parser.py
  python/tests/test_aac/plugins/gen_plugin/my_project.aac
  python/tests/test_aac/plugins/gen_plugin/test_gen_plugin.py
Labels: added

#866 Migrate Build Chain in Core AaC Repo
  .github/workflows/python-build-and-lint.yml
  README.md
  python/MANIFEST.in
  python/pyproject.toml
  python/secure_install/pipeline_scripts/create_install_archive.bash
  python/secure_install/pipeline_scripts/create_install_archive.bat
  python/src/aac/__init__.py
  python/tests/__init__.py
  python/tests/test_aac/context/test_definition_parser.py
  python/tests/test_aac/context/test_language_context.py
  python/tests/test_aac/in_out/test_paths.py
  python/tox.ini
Labels: added

#868 Migrate build chain
  .github/workflows/python-build-and-lint.yml
  README.md
  python/MANIFEST.in
  python/pyproject.toml
  python/secure_install/pipeline_scripts/create_install_archive.bash
  python/secure_install/pipeline_scripts/create_install_archive.bat
  python/src/aac/__init__.py
  python/tests/__init__.py
  python/tests/test_aac/context/test_definition_parser.py
  python/tests/test_aac/context/test_language_context.py
  python/tests/test_aac/in_out/test_paths.py
  python/tox.ini
Labels: added

#870 Fix doc deplopyment
  .github/workflows/deploy-pages.yml
  python/src/aac/__init__.py
Labels: fixed

#871 Update Workflows
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/DOCUMENTATION-REQUEST.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/SIMPLE-TASK.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-pages.yml
  .github/workflows/issues2md.yml
  .github/workflows/python-build-and-lint.yml
  .github/workflows/python-cross-platform-support.yml
  .github/workflows/python-deploy-artifacts.yml
  .github/workflows/python-test-python-version.yml
  python/secure_install/install_scripts/install_aac_air_gap.bash
  python/secure_install/install_scripts/install_aac_air_gap.bat
  python/secure_install/install_scripts/install_aac_verified_index.bash
  python/secure_install/install_scripts/install_aac_verified_index.bat
  python/src/aac/__init__.py
Labels: added, changed, removed

#872 Standardize test init files
  python/src/aac/__init__.py
  python/tests/__init__.py
  python/tests/test_aac/__init__.py
  python/tests/test_aac/context/__init__.py
  python/tests/test_aac/execute/__init__.py
  python/tests/test_aac/in_out/__init__.py
  python/tests/test_aac/in_out/files/__init__.py
  python/tests/test_aac/plugins/__init__.py
  python/tests/test_aac/plugins/aac_primitives/__init__.py
  python/tests/test_aac/plugins/gen_plugin/__init__.py
  python/tests/test_aac/plugins/no_ext_for_final/__init__.py
  python/tests/test_aac/plugins/root_schema_must_have_name/__init__.py
  python/tests/test_aac/plugins/unique_root_keys/__init__.py
  python/tests/test_aac/plugins/version/__init__.py
Labels: changed
